version: "3"

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=bloggy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ayanniyi20
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  broker:
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"