# Generated by Django 5.0.4 on 2024-04-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates Whether A User Is Active",
                verbose_name="Active",
            ),
        ),
    ]
