# Generated by Django 5.0.4 on 2024-05-13 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0002_preference_blogger_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogger",
            name="preferences",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="auths.preference",
                verbose_name="Preferences",
            ),
        ),
    ]
