# Generated by Django 5.0.4 on 2024-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Password"),
        ),
    ]
