# Generated by Django 5.0.4 on 2024-04-22 01:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0004_alter_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        db_index=True, max_length=120, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                (
                    "username",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates Whether A User Is Active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Designates Whether A User Is An Admin",
                        verbose_name="Admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Blogger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        db_index=True, max_length=120, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                (
                    "username",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates Whether A User Is Active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Designates Whether A User Is An Admin",
                        verbose_name="Admin",
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(max_length=1000, verbose_name="Profile Image Url"),
                ),
            ],
            options={
                "verbose_name": "Blogger",
                "verbose_name_plural": "Bloggers",
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
