# Generated by Django 5.0.4 on 2024-04-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0005_superuser_blogger_delete_user"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auths.blogger",
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="blogger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auths.blogger",
                verbose_name="Blogger",
            ),
        ),
        migrations.DeleteModel(
            name="Blogger",
        ),
    ]
