# Generated by Django 5.0.4 on 2024-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_like_by_alter_comment_post_alter_like_post_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="amount",
        ),
        migrations.AddField(
            model_name="post",
            name="number_of_likes",
            field=models.IntegerField(default=0, verbose_name="Number Of Likes"),
            preserve_default=False,
        ),
    ]
