# Generated by Django 5.0.4 on 2024-04-29 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0001_initial"),
        ("blog", "0003_remove_like_amount_post_number_of_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="by",
        ),
        migrations.AddField(
            model_name="like",
            name="creator",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                to="auths.blogger",
                verbose_name="Creator",
            ),
            preserve_default=False,
        ),
    ]
