# Generated by Django 5.0.4 on 2024-04-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_like_by_like_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="number_of_likes",
            field=models.IntegerField(default=0, verbose_name="Number Of Likes"),
        ),
    ]
