# Generated by Django 5.0.4 on 2024-05-05 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_number_of_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default=1, unique=True, verbose_name="Tag"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(
                related_name="tags",
                related_query_name="tag",
                to="blog.post",
                verbose_name="Posts",
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                ("name", models.CharField(unique=True, verbose_name="Category")),
                (
                    "posts",
                    models.ManyToManyField(
                        related_name="category", to="blog.post", verbose_name="Posts"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
